<a href="https://colab.research.google.com/github/msvt37/HW_11_Risky_Business/blob/main/credit_risk_ensemble.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ensemble Learning

## Initial Imports

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [3]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

In [4]:
#from google.colab import drive
#drive.mount('/content/drive')

Mounted at /content/drive

## Read the CSV and Perform Basic Data Cleaning

In [4]:
# Load the data
file_path = Path('LoanStats_2019Q1.csv')
df = pd.read_csv(file_path)

# Preview the data
df.head(15)

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N
5,25000.0,0.1797,634.43,MORTGAGE,90000.0,Source Verified,Mar-2019,low_risk,n,18.49,...,93.1,66.7,0.0,0.0,550717.0,418934.0,18800.0,369051.0,N,N
6,20400.0,0.2000,540.48,RENT,51315.0,Source Verified,Mar-2019,low_risk,n,25.63,...,100.0,0.0,1.0,0.0,40023.0,23469.0,3500.0,27523.0,N,N
7,10000.0,0.1557,349.46,OWN,66000.0,Source Verified,Mar-2019,low_risk,n,9.00,...,100.0,16.7,0.0,0.0,29300.0,22377.0,8400.0,12500.0,N,N
8,14000.0,0.0881,443.96,RENT,45000.0,Not Verified,Mar-2019,low_risk,n,10.24,...,100.0,0.0,0.0,0.0,25100.0,9724.0,12100.0,3000.0,N,N
9,10000.0,0.1474,345.39,RENT,63295.0,Verified,Mar-2019,low_risk,n,39.34,...,97.2,71.4,0.0,0.0,119822.0,102924.0,15300.0,80722.0,N,N
10,8500.0,0.0819,267.11,RENT,75000.0,Not Verified,Mar-2019,low_risk,n,17.31,...,100.0,0.0,0.0,0.0,75000.0,57756.0,18000.0,57000.0,N,N
11,10000.0,0.1171,330.76,RENT,54000.0,Not Verified,Mar-2019,low_risk,n,21.49,...,100.0,0.0,0.0,0.0,152500.0,42343.0,85000.0,65500.0,N,N
12,30000.0,0.1033,642.30,MORTGAGE,100000.0,Source Verified,Mar-2019,low_risk,n,8.00,...,100.0,0.0,0.0,0.0,50200.0,17323.0,29200.0,20000.0,N,N
13,15800.0,0.1640,387.60,MORTGAGE,62000.0,Source Verified,Mar-2019,low_risk,n,8.44,...,100.0,50.0,0.0,0.0,195700.0,18726.0,15900.0,4100.0,N,N
14,18000.0,0.1557,433.63,MORTGAGE,60000.0,Verified,Mar-2019,low_risk,n,62.80,...,100.0,25.0,0.0,0.0,196496.0,170509.0,10200.0,73796.0,N,N

In [ ]:
# Tried using histogram plots to see indiv rows and amount of data present.
%matplotlib inline
import matplotlib.pyplot as plt
df.hist(bins=50, figsize=(20,15))
plt.show()

In [5]:
#Encoding the following columns to remove strings
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(df['home_ownership'])
df['home_ownership'] = le.transform(df['home_ownership'])

le.fit(df['verification_status'])
df['verification_status'] = le.transform(df['verification_status'])

le.fit(df['loan_status'])
df['loan_status'] = le.transform(df['loan_status'])

le.fit(df['application_type'])
df['application_type'] = le.transform(df['application_type'])

le.fit(df['pymnt_plan'])
df['pymnt_plan'] = le.transform(df['pymnt_plan'])

le.fit(df['issue_d'])
df['issue_d'] = le.transform(df['issue_d'])

le.fit(df['initial_list_status'])
df['initial_list_status'] = le.transform(df['initial_list_status'])

In [6]:
# Some columns seem to have no meaningful data...?
drops = df.columns[df.max() == 0]
drops

Index(['pymnt_plan', 'recoveries', 'collection_recovery_fee', 'acc_now_delinq',
       'num_tl_120dpd_2m', 'num_tl_30dpd', 'tax_liens'],
      dtype='object')

In [7]:
df.drop(['recoveries', 'collection_recovery_fee', 'acc_now_delinq',
       'num_tl_120dpd_2m', 'num_tl_30dpd', 'tax_liens', 'issue_d', 'initial_list_status', 'next_pymnt_d'], axis=1, inplace=True)

In [8]:
# Do we need this column?
df['pymnt_plan'].value_counts()

0    68817
Name: pymnt_plan, dtype: int64

In [9]:
#Based on numbers above, no.
df.drop(['pymnt_plan'], axis=1, inplace=True)

In [10]:
#both of these columns only have zeros, drop?
df['hardship_flag'].value_counts()
df['debt_settlement_flag'].value_counts()

N    68817
Name: debt_settlement_flag, dtype: int64

In [11]:
df.drop(['hardship_flag', 'debt_settlement_flag'], axis=1, inplace=True)

## Split the Data into Training and Testing

In [12]:
# Create our features
X = df.drop(columns='loan_status')

# Create our target
y = df['loan_status']

In [14]:
X.describe()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,dti,delinq_2yrs,inq_last_6mths,open_acc,...,num_sats,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
count,68817.000000,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,6.881700e+04,6.881700e+04,68817.000000,6.881700e+04
mean,16677.594562,0.127718,480.652863,1.812779,8.821371e+04,0.669994,21.778153,0.217766,0.497697,12.587340,...,12.571995,0.052138,2.219423,95.057627,30.626217,0.125972,2.100332e+05,6.133843e+04,29734.128558,5.572240e+04
std,10277.348590,0.048130,288.062432,0.941313,1.155800e+05,0.719105,20.199244,0.718367,0.758122,6.022869,...,6.021318,0.390633,1.897432,8.326426,33.631463,0.336732,1.928088e+05,5.738798e+04,26795.394232,5.095845e+04
min,1000.000000,0.060000,30.890000,0.000000,4.000000e+01,0.000000,0.000000,0.000000,0.000000,2.000000,...,2.000000,0.000000,0.000000,20.000000,0.000000,0.000000,3.600000e+03,2.350000e+02,100.000000,1.270000e+02
25%,9000.000000,0.088100,265.730000,1.000000,5.000000e+04,0.000000,13.890000,0.000000,0.000000,8.000000,...,8.000000,0.000000,1.000000,93.000000,0.000000,0.000000,6.697700e+04,2.650300e+04,11600.000000,2.288000e+04
50%,15000.000000,0.118000,404.560000,1.000000,7.300000e+04,1.000000,19.760000,0.000000,0.000000,11.000000,...,11.000000,0.000000,2.000000,100.000000,20.000000,0.000000,1.467100e+05,4.535700e+04,22100.000000,4.200000e+04
75%,24000.000000,0.155700,648.100000,3.000000,1.040000e+05,1.000000,26.660000,0.000000,1.000000,16.000000,...,16.000000,0.000000,3.000000,100.000000,50.000000,0.000000,3.036400e+05,7.657000e+04,39300.000000,7.249900e+04
max,40000.000000,0.308400,1676.230000,3.000000,8.797500e+06,2.000000,999.000000,18.000000,5.000000,72.000000,...,72.000000,18.000000,19.000000,100.000000,100.000000,4.000000,3.292782e+06,1.295455e+06,509400.000000,1.426964e+06

In [15]:
# Check the balance of our target values
y.value_counts()

1    68470
0      347
Name: loan_status, dtype: int64

In [16]:
# Split the X and y into X_train, X_test, y_train, y_test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)
X_train

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,dti,delinq_2yrs,inq_last_6mths,open_acc,...,num_sats,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
39692,10000.0,0.1131,328.86,1,49000.0,1,24.54,0.0,0.0,10.0,...,10.0,0.0,2.0,100.0,0.0,1.0,309140.0,56262.0,9500.0,54197.0
37830,21000.0,0.1072,684.74,3,57400.0,0,34.52,0.0,0.0,12.0,...,12.0,0.0,0.0,100.0,0.0,0.0,98100.0,35707.0,64700.0,30000.0
64531,35000.0,0.0881,1109.90,2,180000.0,0,3.01,0.0,2.0,7.0,...,7.0,0.0,0.0,94.7,0.0,0.0,327877.0,1222.0,41500.0,26177.0
28730,20000.0,0.0819,628.49,2,80000.0,1,26.51,0.0,0.0,15.0,...,15.0,0.0,1.0,90.0,0.0,0.0,143541.0,81162.0,14500.0,111641.0
35102,12600.0,0.1356,427.96,1,71000.0,1,22.38,1.0,2.0,7.0,...,7.0,0.0,4.0,88.9,0.0,0.0,316682.0,33433.0,26500.0,50182.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18872,35000.0,0.0881,1109.90,1,400000.0,1,13.79,0.0,1.0,17.0,...,17.0,0.0,7.0,97.6,0.0,1.0,631699.0,189478.0,28600.0,244399.0
6415,16800.0,0.0881,532.76,2,31000.0,2,20.48,0.0,0.0,3.0,...,3.0,0.0,2.0,100.0,0.0,0.0,20400.0,11771.0,3500.0,16900.0
12632,25000.0,0.1102,818.71,1,90000.0,0,15.27,1.0,0.0,18.0,...,18.0,0.0,3.0,96.6,12.5,0.0,195681.0,40625.0,40600.0,33181.0
24022,14000.0,0.1072,456.49,1,180000.0,0,12.35,2.0,0.0,10.0,...,10.0,0.0,2.0,73.9,50.0,0.0,754884.0,49607.0,11000.0,63655.0
44756,15000.0,0.0702,463.30,1,89000.0,0,13.30,0.0,0.0,7.0,...,7.0,0.0,0.0,100.0,0.0,0.0,197210.0,38246.0,33100.0,31962.0

## Data Pre-Processing

Scale the training and testing data using the `StandardScaler` from `sklearn`. Remember that when scaling the data, you only scale the features data (`X_train` and `X_testing`).

In [17]:
# Create the StandardScaler instance
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [18]:
# Fit the Standard Scaler with the training data
# When fitting scaling functions, only train on the training dataset
scaler.fit(X_train)

StandardScaler()

In [19]:
# Scale the training and testing data
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

## Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Display the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier only, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [38]:
# Resample the training data with the BalancedRandomForestClassifier.  Did not run in Colab, was able to run locally
from imblearn.ensemble import BalancedRandomForestClassifier
brf = BalancedRandomForestClassifier(n_estimators=100, random_state=1)
brf.fit(X_train, y_train)
predictions = brf.predict(X_test)

In [39]:
# Calculate the balanced accuracy score
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
acc_score = accuracy_score(y_test, predictions)
print(acc_score)

0.8320836965998256

In [40]:
# Display the confusion matrix
cm = confusion_matrix(y_test, predictions)
cm_df = pd.DataFrame(
    cm, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"]
)
print(cm_df)

          Predicted 0  Predicted 1
Actual 0           50           37
Actual 1         2852        14266

In [41]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, predictions))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.02      0.57      0.83      0.03      0.69      0.47        87
          1       1.00      0.83      0.57      0.91      0.69      0.49     17118

avg / total       0.99      0.83      0.58      0.90      0.69      0.49     17205

In [42]:
# List the features sorted in descending order by feature importance
importances = brf.feature_importances_
importances_sorted = sorted(zip(brf.feature_importances_, X.columns), reverse=True)
importances_sorted[:10]

[(0.07330622237479142, 'total_rec_prncp'),
 (0.06643133040535117, 'total_pymnt_inv'),
 (0.05817463012847855, 'last_pymnt_amnt'),
 (0.0580827393914113, 'total_pymnt'),
 (0.05501505789430453, 'total_rec_int'),
 (0.028413439361595193, 'int_rate'),
 (0.02082875892962306, 'mo_sin_old_rev_tl_op'),
 (0.020673102848775944, 'mths_since_recent_inq'),
 (0.020015562130641363, 'out_prncp'),
 (0.01930004886683556, 'bc_util')]

### Easy Ensemble Classifier

In [48]:
# Train the Classifier
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=0)
rf_model = rf_model.fit(X_train, y_train)
predictions_rf = rf_model.predict(X_test)

In [56]:
# Calculated the balanced accuracy score
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
acc_score_rf = accuracy_score(y_test, predictions_rf)
print(f"Accuracy Score : {acc_score_rf}")

Accuracy Score : 0.995931415286254

In [55]:
# Display the confusion matrix
cm_rf = confusion_matrix(y_test, predictions_rf)
cm_df_rf = pd.DataFrame(
    cm_rf, index=["Actual 0", "Actual 1"], columns=["Predicted 0", "Predicted 1"]
)
print("Confusion Matrix")
display(cm_df_rf)

Confusion Matrix

          Predicted 0  Predicted 1
Actual 0           29           58
Actual 1           12        17106

In [57]:
# Print the imbalanced classification report
print("Classification Report")
print(classification_report_imbalanced(y_test, predictions_rf))

Classification Report
                   pre       rec       spe        f1       geo       iba       sup

          0       0.71      0.33      1.00      0.45      0.58      0.31        87
          1       1.00      1.00      0.33      1.00      0.58      0.36     17118

avg / total       1.00      1.00      0.34      1.00      0.58      0.36     17205

In [53]:
importances2 = rf_model.feature_importances_
importances_sorted2 = sorted(zip(rf_model.feature_importances_, X.columns), reverse=True)
importances_sorted2[:10]

[(0.07937523421121714, 'total_rec_prncp'),
 (0.07399269360597781, 'total_rec_int'),
 (0.06278417546617812, 'total_pymnt_inv'),
 (0.060918042039024345, 'total_pymnt'),
 (0.05301715441547612, 'last_pymnt_amnt'),
 (0.020261645508119833, 'dti'),
 (0.018439677409502506, 'mo_sin_old_rev_tl_op'),
 (0.018263002531530695, 'tot_hi_cred_lim'),
 (0.018172568594754045, 'bc_open_to_buy'),
 (0.01808116436299988, 'mo_sin_old_il_acct')]

### Final Questions

1. Which model had the best balanced accuracy score?

    The Random Forest Classifier appears to have the better score with: Accuracy Score : 0.995931415286254 .

2. Which model had the best recall score? (% of positive caught)

    The Balanced Random Forest Classifier had the best recall score.

3. Which model had the best geometric mean score?

   The Balanced Random Forest Classifies had the best geometric mean score.

4. What are the top three features?

For the Random Forest:
(0.07937523421121714, 'total_rec_prncp'),
(0.07399269360597781, 'total_rec_int'),
(0.06278417546617812, 'total_pymnt_inv')
 
For the Balanced Random Forest:

(0.07330622237479142, 'total_rec_prncp'),
(0.06643133040535117, 'total_pymnt_inv'),
(0.05817463012847855, 'last_pymnt_amnt'),